# Encoding :
categariol data   convert  into numerical data .

--> one hot encoding :------------------------------ use : when short number of the data is present  (ex - male & female , Yes & No)

In [4]:
import pandas as pd
data = {
    "name" : ["A","B","C","D","E","F","G"],
    "gender" : ["male","female","male","female","male","female","male"]
}
df = pd.DataFrame(data)
print(df)

  name  gender
0    A    male
1    B  female
2    C    male
3    D  female
4    E    male
5    F  female
6    G    male

In [6]:
df.isnull().sum()

name      0
gender    0
dtype: int64

# : encoding by get dummies

In [7]:
pd.get_dummies(df['gender'])            # check by info then shows  boolean data

   female   male
0   False   True
1    True  False
2   False   True
3    True  False
4   False   True
5    True  False
6   False   True

#: encoding by OneHotEncoder class

In [9]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe_e = ohe.fit_transform(df[['gender']])         # give sparse matrix
print(ohe_e)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (7, 2)>
  Coords	Values
  (0, 1)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 1)	1.0

In [10]:
ohe_e1 = ohe_e.toarray()
print(ohe_e1)

[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]

In [11]:
pd.DataFrame(ohe_e1,columns = ohe.categories_)

  female male
0    0.0  1.0
1    1.0  0.0
2    0.0  1.0
3    1.0  0.0
4    0.0  1.0
5    1.0  0.0
6    0.0  1.0

# Sparse Matrix  :  is the matrix in which most of the element is 0 & 1

In [ ]:
#handle missing values :
import pandas as pd
import numpy as np

data = {
    "colors" : ['red','green','blue','orange','green','blue',np.nan]
}
df = pd.DataFrame(data)
print(df)


#handle null values :
df.dropna(inplace = True)
print(df)

   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
6     NaN
   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue

In [ ]:
# label Encoding :
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['colors_encoder'] = le.fit_transform(df['colors'])
print(df)

   colors  colors_encoder
0     red               3
1   green               1
2    blue               0
3  orange               2
4   green               1
5    blue               0

In [ ]:
# one hot encoding :
from skelarn.preprocessing import OneHotEncoder
print(df)

# drop cols of label encoding
if 'colors_encoder' in df.keys():
  df.drop(columns = ['colors_encoder'],inplace = True)
  print(df)

ModuleNotFoundError: No module named 'skelarn'

In [ ]:
# one host encoding :(by the help of sklearn) :
df_encoder  = pd.get_dummies(df['colors'])
print(df_encoder)

    blue  green  orange    red
0  False  False   False   True
1  False   True   False  False
2   True  False   False  False
3  False  False    True  False
4  False   True   False  False
5   True  False   False  False

In [ ]:
# combination of handle missing values |label encoding  and  onehostEncoding
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

data = {
    "age":[12,13,14,15,16,17,np,nan],
    "gender":["male","female","male","female","male","female",None],
    "name": ['A','B','C','D','E','F','G'],

}
df = pd.DataFrame(data)

# handle missing values
df['age'] = df['age'].fillna(df['age'].mean())
df.dropna(subset = ['gender'],inplace= True)
print(df)

# label encoding
le = LabelEncoder()
df['gender_1'] = le.fit_transform(df['gender'])
print(df)

# one hot encoding
oe = OneHotEncoder()
oe_e = oe.fit_transform(df[['gender']])
df_oe = pd.DataFrame(oe_e.toarray(),columns = le.classes_)
print(df_oe)

 🐾